entryPoints:
  web:
    address: ":80"

providers:
  docker:
    exposedByDefault: false
#  nacos:
#    endpoints:
#      - "mall-nacos:8848"
#    refreshInterval: 10s
#    namespace: "087dbe1b-e6f2-488b-97b4-1fbe5f510086"               # 指定 Nacos 的命名空间
#    username: "nacos"         # Nacos 用户名
#    password: "123456"         # Nacos 密码

api:
  dashboard: true
  insecure: true
